alias ls='ls --color=auto -lv'

alias pac='yaourt'
alias pacS='yaourt -S'
alias pacSc='yaourt -Sc'
alias pacScc='yaourt -Scc'
alias pacSs='yaourt -Ss'
alias pacSi='yaourt -Si'
alias pacSy='yaourt -Sy'
alias pacSyu='yaourt -Syu'
alias pacSyua='yaourt -Syua'
alias pacSyy='yaourt -Syy'
alias pacSyyu='yaourt -Syyu'
alias pacSyyua='yaourt -Syyua'
alias pacR='yaourt -R'
alias pacRs='yaourt -Rsc'
alias pacRdd='yaourt -Rdd'
alias pacRdds='yaourt -Rddsc'
alias pacQ='yaourt -Qs'
alias pacQm='yaourt -Qm'
alias pacQdt='yaourt -Qdt'
alias pacU='yaourt -U'

alias free='free -m'

alias x='sudo'

alias gcc='gcc -std=c11'
alias g++='g++ -std=c++11'

PS1='\[\e[1;34m\]\h\[\e[m\] \[\e[1;35m\]\W\[\e[m\]\[\e[0;31m\] \$\[\e[m\] '
